In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/new-york-fire-department/Open-Data-Dictionary-FDNY_Firehouses.xlsx
/kaggle/input/new-york-fire-department/socrata_metadata_fdny-monthly-response-times.json
/kaggle/input/new-york-fire-department/Monthly_Response_Time_Data_Dictionary.xlsx
/kaggle/input/new-york-fire-department/fdny-line-of-duty-deaths.csv
/kaggle/input/new-york-fire-department/socrata_metadata_fdny-line-of-duty-deaths.json
/kaggle/input/new-york-fire-department/socrata_metadata_fdny-firehouse-listing.json
/kaggle/input/new-york-fire-department/fdny-firehouse-listing.csv
/kaggle/input/new-york-fire-department/Open-Data-Dictionary-FDNY_Line_of_Duty_Deaths.xlsx
/kaggle/input/new-york-fire-department/fdny-monthly-response-times.csv

In [6]:
df =  df = pd.read_csv('/kaggle/input/new-york-fire-department/fdny-monthly-response-times.csv', skiprows=1)

In [7]:
df.describe

<bound method NDFrame.describe of       2009/07  All Fire/Emergency Incidents       Citywide  40850  04:27
0     2009/07  All Fire/Emergency Incidents      Manhattan  10709  04:32
1     2009/07  All Fire/Emergency Incidents          Bronx   8137  04:37
2     2009/07  All Fire/Emergency Incidents  Staten Island   2205  04:45
3     2009/07  All Fire/Emergency Incidents       Brooklyn  11505  04:01
4     2009/07  All Fire/Emergency Incidents         Queens   8294  04:43
...       ...                           ...            ...    ...    ...
4362  FY 2017              Structural Fires      Manhattan   5669  04:26
4363  FY 2017              Structural Fires          Bronx   5829  04:22
4364  FY 2017              Structural Fires  Staten Island   1266  04:28
4365  FY 2017              Structural Fires       Brooklyn   7949  03:42
4366  FY 2017              Structural Fires         Queens   5362  04:34

[4367 rows x 5 columns]>

In [8]:
df.head(3)

   2009/07  All Fire/Emergency Incidents       Citywide  40850  04:27
0  2009/07  All Fire/Emergency Incidents      Manhattan  10709  04:32
1  2009/07  All Fire/Emergency Incidents          Bronx   8137  04:37
2  2009/07  All Fire/Emergency Incidents  Staten Island   2205  04:45

In [9]:
df.columns

Index(['2009/07', 'All Fire/Emergency Incidents', 'Citywide', '40850',
       '04:27'],
      dtype='object')

In [10]:
df.index

RangeIndex(start=0, stop=4367, step=1)

In [11]:
df.count()

2009/07                         4367
All Fire/Emergency Incidents    4367
Citywide                        4367
40850                           4367
04:27                           4367
dtype: int64

In [12]:
df.dtypes

2009/07                         object
All Fire/Emergency Incidents    object
Citywide                        object
40850                            int64
04:27                           object
dtype: object

In [14]:
group_byBorugh = df.groupby('Citywide')

In [15]:
#FDNY for each Borough 
group_byBorugh.size()

Citywide
Bronx            728
Brooklyn         728
Citywide         727
Manhattan        728
Queens           728
Staten Island    728
dtype: int64

In [17]:
#FDNY for info for Manhattan 
Manhattan_fdny = group_byBorugh.get_group('Manhattan')

In [18]:
Manhattan_fdny

      2009/07  All Fire/Emergency Incidents   Citywide  40850  04:27
0     2009/07  All Fire/Emergency Incidents  Manhattan  10709  04:32
6     2009/07                   False Alarm  Manhattan    474  04:07
12    2009/07           Medical Emergencies  Manhattan   4895  04:17
18    2009/07           Medical False Alarm  Manhattan    110  04:18
24    2009/07        NonMedical Emergencies  Manhattan   4446  04:51
...       ...                           ...        ...    ...    ...
4338  FY 2017           Medical Emergencies  Manhattan  76014  04:57
4344  FY 2017           Medical False Alarm  Manhattan    677  05:01
4350  FY 2017        NonMedical Emergencies  Manhattan  67945  05:35
4356  FY 2017           NonStructural Fires  Manhattan   4043  04:44
4362  FY 2017              Structural Fires  Manhattan   5669  04:26

[728 rows x 5 columns]